name: laza_ecommerce
description: A simplified, functional e-commerce mobile app built with Flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.2

  # State Management
  provider: ^6.1.2

  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.17.5

  # HTTP
  http: ^1.2.0

  # Image
  cached_network_image: ^3.3.1

  # Local Storage
  shared_preferences: ^2.2.2

  # UI Enhancements
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.0

  # Validation
  email_validator: ^2.1.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
